package com.go.paydo.entities

class Operation{

    /**
    * TODO(1): Create an "Operation" entity data class.
    * TODO(2): Add a couple of columns
    * TODO(3): Use the annotations to create a Room Entity
    * TODO(4): Make the primary Key Autogenerated
    */

}